### ISSUE TITLE
Rails3 unobstructive JS doesn't work

### ISSUE THREAD

**Issue by sserdyuk** [bernerdschaefer/akephalos#17]
New Rails3 style AJAX forms are not recognized and the form gets submitted via a regular http method.

**Comment by bernerdschaefer** [comment]
Could you give a little more detail for this? Is this just normal :remote => true? Are you specifying a data type? Also, what library are you using (jquery, prototype)?

Thanks

**Comment by sserdyuk** [comment]
Yes, just normal :remote => true. jQuery http://github.com/sserdyuk/rails3-mongodb-mongoid-cucumber-rspec-factory_girl-spork-capybara-capybara-envjs/blob/master/public/javascripts/jquery.js with a driver http://github.com/sserdyuk/rails3-mongodb-mongoid-cucumber-rspec-factory_girl-spork-capybara-capybara-envjs/blob/master/public/javascripts/rails.js

**Comment by zenom** [comment]
This might be similar to the padrino ticket as well since that is a similar situation using UJS.

**Comment by bjeanes** [comment]
Perhaps the page isn't waiting for all the assets to load before continuing with the next step?

**Comment by bernerdschaefer** [comment]
I'm closing this issue. Please use #10 to track this. Here's the latest update from there:

I've narrowed down this issue to a bug in HtmlUnit: https://sourceforge.net/tracker/?func=detail&aid=3072866&group_id=47038&atid=448266

In rails.js, this comes before the $('form[data-remote]') handler:

```
$('a[data-confirm],input[data-confirm]').live('click', function () { // ....
```

For some reason, this prevents the other event handlers from running, which is why the form is posting directly instead of using ajax. Hopefully this issue will be resolved soon and this will work as expected.

**Comment by sserdyuk** [comment]
Thank you!
